{
 "title": "HAProxy OC Ingress Overview",
 "tags": [
  "SLI",
  "SLO"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(sli:apiserver_request_duration_seconds:trend:1m, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(time() - haproxy_process_start_time_seconds{cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(haproxy_process_start_time_seconds{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Instances Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(haproxy_process_start_time_seconds{cluster=~\"$cluster\"})"
    },
    { "expr": "1" }
   ]
  },
  {
   "title": "Response Errors rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_http_responses_total{code=~\"4xx|5xx\",cluster=~\"$cluster\"}[$__interval]) / rate(haproxy_frontend_http_responses_total{cluster=~\"$cluster\"}[$__interval])",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "Backends OK",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "avg by (route)(haproxy_backend_up{cluster=~\"$cluster\",route!=\"\"})"
    }
   ]
  },
  {
   "title": "Down Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_downtime_seconds_total{cluster=~\"$cluster\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Connections error rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_connections_total{cluster=~\"$cluster\"}[$__interval]) - rate(haproxy_server_connection_errors_total{cluster=~\"$cluster\"}[$__interval])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Failed health checks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_check_failures_total{cluster=~\"$cluster\"}[$__interval])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Frontend sessions rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (frontend) (haproxy_frontend_current_sessions{cluster=~\"$cluster\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Current Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (route)(haproxy_server_current_queue{server!=\"\",cluster=~\"$cluster\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Avg Response Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (route)(haproxy_server_http_average_response_latency_milliseconds{service!=\"\",cluster=~\"$cluster\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_process_cpu_seconds_total{cluster=~\"$cluster\"}[$__interval])",
     "legendFormat": "{{container_id}}"
    }
   ]
  },
  {
   "title": "Max open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "haproxy_process_max_fds{cluster=~\"$cluster\"}",
     "legendFormat": "{{container_id}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "haproxy_process_resident_memory_bytes{cluster=~\"$cluster\"}",
     "legendFormat": "{{container_id}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "haproxy_process_virtual_memory_bytes{cluster=~\"$cluster\"}",
     "legendFormat": "{{container_id}}"
    }
   ]
  },
  {
   "title": "Frontend Bytes In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (frontend) (rate(haproxy_frontend_bytes_in_total{cluster=~\"$cluster\"}[$__interval]))",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "Frontend Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (frontend) (rate(haproxy_frontend_connections_total{cluster=~\"$cluster\"}[$__interval]))",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "Frontend Bytes Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (frontend) (rate(haproxy_frontend_bytes_out_total{cluster=~\"$cluster\"}[$__interval]))",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "Frontend HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (frontend,code) (rate(haproxy_frontend_http_responses_total{cluster=~\"$cluster\"}[$__interval]))",
     "legendFormat": "{{frontend}}: {{code}}"
    }
   ]
  }
 ]
}